name: "New Resource Pack Request"
description: "Request a brand-new resource pack that does not fit into existing packs\nRequests may or may not be fulfilled, at the discretion of the author (Furglitch)"
title: "[New] '{{pack_name}}'"
labels: [newpack]
assignees: []
body:
- type: markdown
  attributes:
    value: |
      **Do NOT remove `'{{pack_name}}'` from the title.**  
      This will be automatically replaced with the information you provide below.
- type: input
  id: pack_name
  attributes:
    label: "Resource pack name"
    description: "Suggest a name for the new resource pack you are requesting"
  validations:
    required: true
- type: input
  id: target_mc_version
  attributes:
    label: "Target Minecraft version"
    description: "Minecraft version this pack should target (e.g. 1.21.1)"
    placeholder: "1.21.1"
  validations:
    required: true
- type: input
  id: target_mod
  attributes:
    label: "Target Mod"
    description: "Mod that this resource pack is intended to support. If it is a vanilla pack, leave this blank."
    placeholder: "Mekanism, Create, etc."
- type: textarea
  id: summary
  attributes:
    label: "Summary / purpose"
    description: "Briefly explain the purpose of the pack and why it cannot fit into an existing pack."
  validations:
    required: true
- type: textarea
  id: assets_scope
  attributes:
    label: "Assets & scope"
    description: "List assets, namespaces, textures, sounds, models, or systems needed and approximate scope/size."
  validations:
    required: true
- type: textarea
  id: implementation_notes
  attributes:
    label: "Implementation notes"
    description: "Notes about how it should be implemented, references to other packs, or example approaches."
- type: input
  id: references
  attributes:
    label: "Reference links (optional)"
    description: "Links to examples, mockups, related issues, or changelogs."
    placeholder: "https://..."
- type: textarea
  id: additional_info
  attributes:
    label: "Additional information"
    description: "Any extra notes, screenshots, constraints, or licensing concerns."