noticably-suspicious:
  - "### Resource pack\n\nNoticably Suspicious"

ping-wheel-portal-2-sound:
  - "### Resource pack\n\nPing Wheel - Portal 2 Sound"

pretty-pretty-pipes:
  - "### Resource pack\n\nPretty Pretty Pipes"

pretty-pretty-pipes-mekanism:
  - "### Resource pack\n\nPretty Pretty Pipes: Mekanism"

utilitarian-upgraded:
  - "### Resource pack\n\nUtilitarian Upgraded"

vending-block-restocked-mandalas-gui:
  - "### Resource pack\n\nVending Block: Restocked - Mandala's GUI"